CREATE TABLE COLABORADOR (
	ID_COLABORADOR SERIAL PRIMARY KEY,
	NOME VARCHAR (50) NOT NULL,
	CPD INT NOT NULL UNIQUE,
	DATA_EMPRESTIMO DATE NOT NULL 
);
CREATE TABLE LIVRO (
	ID_LIVRO SERIAL PRIMARY KEY,
	ORIGEM VARCHAR (50) NOT NULL,
	DATA_AQUISICAO DATE NOT NULL, 
	AUTOR VARCHAR (50) NOT NULL,
	NOME VARCHAR (50) NOT NULL
);
CREATE TABLE GENERO (
	ID_GENERO SERIAL PRIMARY KEY,
	DESCRICAO_GENERO VARCHAR (60) NOT NULL
);
CREATE TABLE COLABORADOR_LIVRO (
	ID_COLABORADOR INT,
	ID_LIVRO INT,
	PRIMARY KEY (ID_COLABORADOR, ID_LIVRO),
	STATUS VARCHAR (20),
	DATA_INICIO_EMPRESTIMO DATE,
	DATA_FIM_EMPRESTIMO DATE,
	CONSTRAINT FK_ID_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR (ID_COLABORADOR),
	CONSTRAINT FK_ID_LIVRO FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO)
);
CREATE TABLE LIVRO_GENERO (
	IDLIVRO_GENERO INT PRIMARY KEY,
	CONSTRAINT FK_ID_LIVRO FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO),
	CONSTRAINT FK_ID_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO)
);